/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carrier4u;

/**
 *
 * @author Mohammed
 */
public class MainInput extends javax.swing.JFrame {

    /**
     * Creates new form MainInput
     */
    public MainInput() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        TotalMinutes = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        TotalText = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        TotalData = new javax.swing.JTextPane();
        BusinessEmail = new javax.swing.JLabel();
        BusinessMailYes = new javax.swing.JRadioButton();
        BusinessMailNo = new javax.swing.JRadioButton();
        MusicStreaming = new javax.swing.JLabel();
        FamilyPlanNo = new javax.swing.JRadioButton();
        FamilyPlanYes = new javax.swing.JRadioButton();
        FamilyPlan = new javax.swing.JLabel();
        InternationalCallingYes = new javax.swing.JRadioButton();
        InternationalCallingNo = new javax.swing.JRadioButton();
        InternationalCalling = new javax.swing.JLabel();
        InternationalTextingNo = new javax.swing.JRadioButton();
        InternationalTextingYes = new javax.swing.JRadioButton();
        InternationalTexting = new javax.swing.JLabel();
        InternetSpeed = new javax.swing.JLabel();
        Internet3G = new javax.swing.JRadioButton();
        Internet2G = new javax.swing.JRadioButton();
        InternetLTE = new javax.swing.JRadioButton();
        SignalStrength = new javax.swing.JLabel();
        RoamingStrength = new javax.swing.JLabel();
        NetworkType = new javax.swing.JLabel();
        DesiredOS = new javax.swing.JLabel();
        MMS = new javax.swing.JLabel();
        LocationBased = new javax.swing.JLabel();
        SignalCoverageSlider = new javax.swing.JSlider();
        RoamingSlider = new javax.swing.JSlider();
        NetworkGSM = new javax.swing.JRadioButton();
        NetworkCDMA = new javax.swing.JRadioButton();
        IOS = new javax.swing.JRadioButton();
        OtherOS = new javax.swing.JRadioButton();
        AndroidOS = new javax.swing.JRadioButton();
        MMSno = new javax.swing.JRadioButton();
        MMSyes = new javax.swing.JRadioButton();
        LocationBasedNo = new javax.swing.JRadioButton();
        LocationBasedYes = new javax.swing.JRadioButton();
        SubmitButton = new javax.swing.JButton();
        MusicSteamingYes = new javax.swing.JRadioButton();
        MusicSteamingNo = new javax.swing.JRadioButton();
        AnalysisOfCarriers = new javax.swing.JButton();

        jRadioButton8.setText("Yes");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });

        jRadioButton7.setText("No");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        jLabel2.setText("Representative View");

        jLabel1.setText("Carrier4U");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setAlignmentX(0.1F);
        jLabel1.setPreferredSize(new java.awt.Dimension(34, 12));
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel3.setText("Total Minutes Desired:");

        jScrollPane2.setViewportView(TotalMinutes);

        jLabel4.setText("Total Data Desired:");

        jScrollPane3.setViewportView(TotalText);

        jLabel5.setText("Total Text Desired:");

        jScrollPane4.setViewportView(TotalData);

        BusinessEmail.setText("Business Email");

        BusinessMailYes.setText("Yes");
        BusinessMailYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusinessMailYesActionPerformed(evt);
            }
        });

        BusinessMailNo.setText("No");
        BusinessMailNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusinessMailNoActionPerformed(evt);
            }
        });

        MusicStreaming.setText("Music Streaming");

        FamilyPlanNo.setText("No");
        FamilyPlanNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FamilyPlanNoActionPerformed(evt);
            }
        });

        FamilyPlanYes.setText("Yes");
        FamilyPlanYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FamilyPlanYesActionPerformed(evt);
            }
        });

        FamilyPlan.setText("Family Plan");

        InternationalCallingYes.setText("Yes");
        InternationalCallingYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InternationalCallingYesActionPerformed(evt);
            }
        });

        InternationalCallingNo.setText("No");
        InternationalCallingNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InternationalCallingNoActionPerformed(evt);
            }
        });

        InternationalCalling.setText("International Calling");

        InternationalTextingNo.setText("No");
        InternationalTextingNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InternationalTextingNoActionPerformed(evt);
            }
        });

        InternationalTextingYes.setText("Yes");
        InternationalTextingYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InternationalTextingYesActionPerformed(evt);
            }
        });

        InternationalTexting.setText("International Texting");

        InternetSpeed.setText("Speed of Internet");

        Internet3G.setText("3G");
        Internet3G.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Internet3GActionPerformed(evt);
            }
        });

        Internet2G.setText("2G");
        Internet2G.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Internet2GActionPerformed(evt);
            }
        });

        InternetLTE.setText("LTE");
        InternetLTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InternetLTEActionPerformed(evt);
            }
        });

        SignalStrength.setText("Importance of Signal Coverage");

        RoamingStrength.setText("Roming");

        NetworkType.setText("Type Of Network");

        DesiredOS.setText("Cell Phone OS");

        MMS.setText("MMS");

        LocationBased.setText("Location Based");

        NetworkGSM.setText("GSM");
        NetworkGSM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NetworkGSMActionPerformed(evt);
            }
        });

        NetworkCDMA.setText("CDMA");
        NetworkCDMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NetworkCDMAActionPerformed(evt);
            }
        });

        IOS.setText("IOS");
        IOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IOSActionPerformed(evt);
            }
        });

        OtherOS.setText("Other");
        OtherOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OtherOSActionPerformed(evt);
            }
        });

        AndroidOS.setText("Andriod");
        AndroidOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AndroidOSActionPerformed(evt);
            }
        });

        MMSno.setText("No");
        MMSno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMSnoActionPerformed(evt);
            }
        });

        MMSyes.setText("Yes");
        MMSyes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMSyesActionPerformed(evt);
            }
        });

        LocationBasedNo.setText("No");
        LocationBasedNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocationBasedNoActionPerformed(evt);
            }
        });

        LocationBasedYes.setText("Yes");
        LocationBasedYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocationBasedYesActionPerformed(evt);
            }
        });

        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        MusicSteamingYes.setText("Yes");
        MusicSteamingYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MusicSteamingYesActionPerformed(evt);
            }
        });

        MusicSteamingNo.setText("No");
        MusicSteamingNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MusicSteamingNoActionPerformed(evt);
            }
        });

        AnalysisOfCarriers.setText("Analyze");
        AnalysisOfCarriers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalysisOfCarriersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(BusinessEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BusinessMailYes)
                        .addGap(12, 12, 12)
                        .addComponent(BusinessMailNo)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(MMS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MMSyes)
                                .addGap(12, 12, 12)
                                .addComponent(MMSno))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addComponent(DesiredOS)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(IOS)
                                        .addGap(12, 12, 12)
                                        .addComponent(AndroidOS))
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addComponent(NetworkType)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(NetworkGSM)))
                                .addGap(12, 12, 12)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NetworkCDMA)
                                    .addComponent(OtherOS)))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(LocationBased)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SubmitButton)
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addComponent(LocationBasedYes)
                                        .addGap(12, 12, 12)
                                        .addComponent(LocationBasedNo)))))
                        .addContainerGap())
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MusicStreaming)
                            .addComponent(FamilyPlan)
                            .addComponent(InternationalCalling)
                            .addComponent(InternationalTexting))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(FamilyPlanYes)
                                .addGap(12, 12, 12)
                                .addComponent(FamilyPlanNo))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(MusicSteamingYes)
                                .addGap(12, 12, 12)
                                .addComponent(MusicSteamingNo))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(InternationalTextingYes)
                                .addGap(12, 12, 12)
                                .addComponent(InternationalTextingNo))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(InternationalCallingYes)
                                .addGap(12, 12, 12)
                                .addComponent(InternationalCallingNo)))
                        .addContainerGap())
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InternetSpeed)
                            .addComponent(RoamingStrength))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(Internet2G)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Internet3G)
                                .addGap(12, 12, 12)
                                .addComponent(InternetLTE))
                            .addComponent(RoamingSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AnalysisOfCarriers)
                    .addComponent(SignalStrength))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(SignalCoverageSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(16, 16, 16)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BusinessEmail)
                    .addComponent(BusinessMailYes)
                    .addComponent(BusinessMailNo))
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MusicSteamingYes)
                            .addComponent(MusicSteamingNo)))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MusicStreaming)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(FamilyPlanYes)
                                    .addComponent(FamilyPlanNo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(InternationalCallingYes)
                                    .addComponent(InternationalCallingNo)))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(FamilyPlan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(InternationalCalling)))
                        .addGap(2, 2, 2)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InternationalTexting)
                            .addComponent(InternationalTextingYes)
                            .addComponent(InternationalTextingNo))))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InternetSpeed)
                    .addComponent(Internet3G)
                    .addComponent(Internet2G)
                    .addComponent(InternetLTE))
                .addGap(32, 32, 32)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SignalStrength)
                    .addComponent(SignalCoverageSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RoamingStrength)
                    .addComponent(RoamingSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NetworkType)
                    .addComponent(NetworkGSM)
                    .addComponent(NetworkCDMA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DesiredOS)
                    .addComponent(IOS)
                    .addComponent(OtherOS)
                    .addComponent(AndroidOS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MMS)
                    .addComponent(MMSyes)
                    .addComponent(MMSno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LocationBasedYes)
                        .addComponent(LocationBasedNo))
                    .addComponent(LocationBased))
                .addGap(32, 32, 32)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubmitButton)
                    .addComponent(AnalysisOfCarriers))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int Verizon = 0;
    int Att = 0;
    int Tmobile = 0;
    int Sprint = 0; 
     
    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
       
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void LocationBasedYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocationBasedYesActionPerformed
        // TODO add your handling code here:
        Verizon++;
        System.out.println("Verizon has the best Network Coverage.");
    }//GEN-LAST:event_LocationBasedYesActionPerformed

    private void LocationBasedNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocationBasedNoActionPerformed
        // TODO add your handling code here:
        Tmobile++;
        System.out.println("T-Mobile should be economical since Location Based was selected No.");
    }//GEN-LAST:event_LocationBasedNoActionPerformed

    private void MMSyesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMSyesActionPerformed
        // TODO add your handling code here:
        Sprint++;
        System.out.println("Sprint Has better MMS prefference to 10MB per transfer.");
    }//GEN-LAST:event_MMSyesActionPerformed

    private void MMSnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMSnoActionPerformed
        // TODO add your handling code here:
        Att++;
        System.out.println("AT&T T-Mobile and Verizon allows upto 1MB per transfer.");
    }//GEN-LAST:event_MMSnoActionPerformed

    private void AndroidOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AndroidOSActionPerformed
        // TODO add your handling code here:
        Tmobile++;
        Att++;
        System.out.println("Android OS has a better Support on GSM carrier which are T-Mobile and AT&T.");
    }//GEN-LAST:event_AndroidOSActionPerformed

    private void OtherOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OtherOSActionPerformed
        Verizon++;
        Att++;
        Tmobile++;
        Sprint++;
        System.out.println("Other OS works better on all Carriers.");
        // TODO add your handling code here:
    }//GEN-LAST:event_OtherOSActionPerformed

    private void IOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IOSActionPerformed
        Verizon++;
        Sprint++;
        System.out.println("Apple iOS works better on CDMA Carriers such as Verizon and Sprint.");
        // TODO add your handling code here:
    }//GEN-LAST:event_IOSActionPerformed

    private void NetworkCDMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NetworkCDMAActionPerformed
        Verizon++;
        Sprint++;
        System.out.println("CDMA Carriers are Verizon and Sprint.");
        // TODO add your handling code here:
    }//GEN-LAST:event_NetworkCDMAActionPerformed

    private void NetworkGSMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NetworkGSMActionPerformed
        Att++;
        Tmobile++;
        System.out.println("GSM Carriers are Tmobile and AT&T.");
        // TODO add your handling code here:
    }//GEN-LAST:event_NetworkGSMActionPerformed

    private void InternetLTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InternetLTEActionPerformed
        Verizon++;
        Tmobile++;
        System.out.println("Best LTE Carriers are T-Mobile and Verizon.");
        // TODO add your handling code here:
    }//GEN-LAST:event_InternetLTEActionPerformed

    private void Internet2GActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Internet2GActionPerformed
        Sprint++;
        System.out.println("Best 2G Carrier is Sprint.");
        // TODO add your handling code here:
    }//GEN-LAST:event_Internet2GActionPerformed

    private void Internet3GActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Internet3GActionPerformed
        Att++;
        System.out.println("Best 3G Carrier is AT&T.");
        // TODO add your handling code here:
    }//GEN-LAST:event_Internet3GActionPerformed

    private void InternationalTextingYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InternationalTextingYesActionPerformed
        Att++;
        Tmobile++;
        System.out.println("T-Mobile and AT&T has better International texting plan since they are global.");
        // TODO add your handling code here:
    }//GEN-LAST:event_InternationalTextingYesActionPerformed

    private void InternationalTextingNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InternationalTextingNoActionPerformed
        Verizon++;
        Sprint++;
        System.out.println("Verizon and Sprint dont offer International texting plan since they are CDMA.");
     // TODO add your handling code here:
    }//GEN-LAST:event_InternationalTextingNoActionPerformed

    private void InternationalCallingNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InternationalCallingNoActionPerformed
         System.out.println("Verizon and Sprint dont offer International Calling since they are CDMA.");
        Verizon++;
        Sprint++;
        
        // TODO add your handling code here:
    }//GEN-LAST:event_InternationalCallingNoActionPerformed

    private void InternationalCallingYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InternationalCallingYesActionPerformed
           System.out.println("T-Mobile and AT&T has better International texting plan since they are global.");
         
        Tmobile++;
        Att++;// TODO add your handling code here:
    }//GEN-LAST:event_InternationalCallingYesActionPerformed

    private void FamilyPlanYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FamilyPlanYesActionPerformed
             System.out.println("T-Mobile and AT&T both offer $100 for 4 lines plan.");
         
        Tmobile++;
        Att++;// TODO add your handling code here:
    }//GEN-LAST:event_FamilyPlanYesActionPerformed

    private void FamilyPlanNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FamilyPlanNoActionPerformed
       System.out.println("Verizon and Sprint have the best single line plans startign at $45.");
        Verizon++;
        Sprint++;
        
       // TODO add your handling code here:
    }//GEN-LAST:event_FamilyPlanNoActionPerformed

    private void BusinessMailNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusinessMailNoActionPerformed
        System.out.println("T-Mobile and AT&T arent best on offering Business and Corporate plans.");
     
        Tmobile++;
        Att++;  // TODO add your handling code here:
    }//GEN-LAST:event_BusinessMailNoActionPerformed

    private void BusinessMailYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusinessMailYesActionPerformed
       System.out.println("Verizon and Sprint have the best corporate emails.");
         Verizon++;
        Sprint++;
        // TODO add your handling code here:
    }//GEN-LAST:event_BusinessMailYesActionPerformed

    private void MusicSteamingYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MusicSteamingYesActionPerformed
         System.out.println("Tmobile offers Music Streaming which doesnt count against your data.");
        
        Tmobile++;
        // TODO add your handling code here:
    }//GEN-LAST:event_MusicSteamingYesActionPerformed

    private void MusicSteamingNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MusicSteamingNoActionPerformed
         System.out.println("Sprint is the only Carrier which still offers unlimited data.");
       //Verizon++;
        Sprint++;
      
         // TODO add your handling code here:
    }//GEN-LAST:event_MusicSteamingNoActionPerformed

    private void AnalysisOfCarriersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalysisOfCarriersActionPerformed
        System.out.println("Verizon has " + Verizon + "points.");
        System.out.println("At&t has " + Att + "points.");
        System.out.println("T-Mobile has " + Tmobile + "points.");
        System.out.println("Sprint has " + Sprint + "points.");
    }//GEN-LAST:event_AnalysisOfCarriersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainInput().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnalysisOfCarriers;
    private javax.swing.JRadioButton AndroidOS;
    private javax.swing.JLabel BusinessEmail;
    private javax.swing.JRadioButton BusinessMailNo;
    private javax.swing.JRadioButton BusinessMailYes;
    private javax.swing.JLabel DesiredOS;
    private javax.swing.JLabel FamilyPlan;
    private javax.swing.JRadioButton FamilyPlanNo;
    private javax.swing.JRadioButton FamilyPlanYes;
    private javax.swing.JRadioButton IOS;
    private javax.swing.JLabel InternationalCalling;
    private javax.swing.JRadioButton InternationalCallingNo;
    private javax.swing.JRadioButton InternationalCallingYes;
    private javax.swing.JLabel InternationalTexting;
    private javax.swing.JRadioButton InternationalTextingNo;
    private javax.swing.JRadioButton InternationalTextingYes;
    private javax.swing.JRadioButton Internet2G;
    private javax.swing.JRadioButton Internet3G;
    private javax.swing.JRadioButton InternetLTE;
    private javax.swing.JLabel InternetSpeed;
    private javax.swing.JLabel LocationBased;
    private javax.swing.JRadioButton LocationBasedNo;
    private javax.swing.JRadioButton LocationBasedYes;
    private javax.swing.JLabel MMS;
    private javax.swing.JRadioButton MMSno;
    private javax.swing.JRadioButton MMSyes;
    private javax.swing.JRadioButton MusicSteamingNo;
    private javax.swing.JRadioButton MusicSteamingYes;
    private javax.swing.JLabel MusicStreaming;
    private javax.swing.JRadioButton NetworkCDMA;
    private javax.swing.JRadioButton NetworkGSM;
    private javax.swing.JLabel NetworkType;
    private javax.swing.JRadioButton OtherOS;
    private javax.swing.JSlider RoamingSlider;
    private javax.swing.JLabel RoamingStrength;
    private javax.swing.JSlider SignalCoverageSlider;
    private javax.swing.JLabel SignalStrength;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JTextPane TotalData;
    private javax.swing.JTextPane TotalMinutes;
    private javax.swing.JTextPane TotalText;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
